# Uncomment the next line to define a global platform for your project

target 'APIExample' do
  use_frameworks!

  pod 'AGEVideoLayout', '1.0.2'
  pod 'AgoraRtcEngine_macOS', '4.2.2'
  pod 'AgoraRtmControl_macOS', :path => './'
  pod 'AgoraUIKit_macOS', :path => './'
end

target 'SimpleFilter' do
  use_frameworks!
    # pod 'sdk', :path => 'sdk.podspec'
  pod 'AgoraRtcEngine_macOS', '4.2.2'
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '10.14'
      xcconfig_path = config.base_configuration_reference.real_path
      xcconfig = File.read(xcconfig_path)
      xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
      File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }
    end
  end
end
